baseURL = "https://tiva-yoga.netlify.app"
title = "Tiva Yoga"
author = "Audrey Viceriat"
languageCode = "fr"
DefaultContentLanguage = "fr"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "UA-12345678-1"

# Disqus Comment System
#disqusShortname = ""

[params]

  showBlog = false
  mainSections = []

  googleFonts = true

  [params.logo]
    main = "img/logo/logo_344x314.png"
    alt = "Tiva Yoga Logo"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-20"

  [params.site]
    name = "Tiva Yoga"
    copyrightLabel = "Tous droits réservés."

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true

  [params.homepage_meta_tags]
    meta_description = "Tiva Yoga, un espace créé par Audrey pour vous accompanger dans votre pratique du yoga"
    meta_og_title = "Tiva Yoga"
    meta_og_type = "website"
    meta_og_url = "https://tiva-yoga.com"
    meta_og_image = "https://tiva-yoga.com/img/logo/logo_344x314.png"
    meta_og_description = "Tiva Yoga. La pause yoga pour toi."

[menu]

  [[menu.main]]
    identifier = "courses"
    name = "Cours de yoga"
    url = "/cours/"
    weight = 1

  [[menu.main]]
    parent = "courses"
    identifier = "courses-group"
    name = "Cours collectifs"
    url = "/cours-collectifs/"
    weight = 1

  [[menu.main]]
    parent = "courses"
    identifier = "courses-private"
    name = "Cours particuliers"
    url = "/cours-particuliers/"
    weight = 2

  [[menu.main]]
    parent = "courses"
    identifier = "courses-kids"
    name = "Cours enfants"
    url = "/cours-enfants/"
    weight = 3

  [[menu.main]]
    parent = "courses"
    identifier = "courses-workshops"
    name = "Ateliers"
    url = "/ateliers/"
    weight = 4

  [[menu.main]]
    parent = "courses"
    identifier = "courses-group"
    name = "Cours collectifs"
    url = "/cours-collectifs/"
    weight = 1

  [[menu.main]]
    identifier = "reserve"
    name = "Réserver"
    url = "/reserver/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "À propos"
    url = "/a-propos/"
    weight = 3

  # Footer Menu
  [[menu.footer]]
    name = "Instagram"
    url = "https://www.instagram.com/tiva_yoga/"
    pre = "<i class='fa-brands fa-instagram text-2xl'></i>"
      weight = 1

  [[menu.footer]]
    name = "Facebook"
    url = "https://www.facebook.com/tiva.yoga/"
    pre = "<i class='fa-brands fa-facebook text-2xl'></i>"
      weight = 2
