baseURL = "https://example.com"
title = "Tiva Yoga"
author = "username"
languageCode = "fr"
DefaultContentLanguage = "fr"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "UA-12345678-1"

# Disqus Comment System
#disqusShortname = ""

[params]

  showBlog = true
  mainSections = ['blog']

  googleFonts = true

  [params.logo]
    main = "img/logo/logo.png"
    alt = "Tiva Yoga Logo"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-14"

  [params.site]
    name = "Tiva Yoga"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true

  [params.homepage_meta_tags]
    meta_description = "Tiva Yoga, un espace créé par Audrey pour vous accompanger dans votre pratique du yoga"
    meta_og_title = "Tiva Yoga"
    meta_og_type = "website"
    meta_og_url = "https://tella.pages.dev"
    meta_og_image = "http://localhost:1313/img/slide/vinyasa.webp"
    meta_og_description = "Tiva Yoga, un espace créé par Audrey pour vous accompanger dans votre pratique du yoga"
    meta_twitter_card = "summary_large_image"
    meta_twitter_site = "@username"
    meta_twitter_creator = "@username"

[menu]

  [[menu.main]]
    identifier = "courses"
    name = "Cours de yoga"
    url = "/cours/"
    weight = 1

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "À propos"
    url = "/a-propos/"
    weight = 3

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 4

  # Footer Menu
  [[menu.footer]]
    #name = "Home"
    #url = "/"
    #  weight = 1

  [[menu.footer]]
    #name = "Github"
    #url = "https://github.com/opera7133/tella"
    #pre = "<i class='icon-github text-2xl'></i>"
    #  weight = 2
